#!/bin/bash
echo
echo "arch-install-script 0.1"
echo 

echo "This is a script to create a minimal and stable gnome setup on arch linux."
echo

#set -e
if [[ $EUID -ne 0 ]]; then
    echo "You must be a root user to run this." 2>&1
    exit 1
fi

read -p "Would you like to start (y/n)? " start

if [ "$start" != "${start#[y]}" ] ; then
	echo "Let's begin!"
	echo //////////////////////////////
	read

	cd
	ls /sys/firmware/efi/efivars
	echo //////////////////////////////
	echo

#	wifi-menu
#	read

	ping -c 3 www.google.ca
	echo //////////////////////////////
	echo
	read

	fdisk -l
	lsblk
	echo //////////////////////////////
	echo
	read
	
	cfdisk
	echo //////////////////////////////
	echo
	
	fdisk -l
	lsblk
	echo //////////////////////////////
	echo
	read

	echo "Done."

else
	echo "Script not started."
fi
